#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# System tray and bars
exec-once = waybar & swaync & hypridle & hyprpaper

# System services
exec-once = /usr/lib/udisks2/udisksd
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Dock
exec-once = nwg-dock
