################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor= eDP-1, 1920x1080@60, 0x0, 1.2
monitor= DP-2, 1920x1080@144, auto-up, 1.0
monitor= HDMI-A-1, 1920x1080@60, auto-up, 1.0

# Monitor toggle script
bind= SUPER, d, exec, ~/.scripts/toggle-monitor.sh

# Fix scaling for XWayland apps (like VSCode)
xwayland {
  force_zero_scaling = true
}
